--Query para nulos en flights
SELECT
  COUNTIF(FL_DATE IS NULL) AS null_FL_DATE,
  COUNTIF(AIRLINE_CODE IS NULL) AS null_AIRLINE_CODE,
  COUNTIF(DOT_CODE IS NULL) AS null_DOT_CODE,
  COUNTIF(FL_NUMBER IS NULL) AS null_FL_NUMBER,
  COUNTIF(ORIGIN IS NULL) AS null_ORIGIN,
  COUNTIF(ORIGIN_CITY IS NULL) AS null_ORIGIN_CITY,
  COUNTIF(DEST IS NULL) AS null_DEST,
  COUNTIF(DEST_CITY IS NULL) AS null_DEST_CITY,
  COUNTIF(CRS_DEP_TIME IS NULL) AS null_CRS_DEP_TIME,
  COUNTIF(DEP_TIME IS NULL) AS null_DEP_TIME,
  COUNTIF(DEP_DELAY IS NULL) AS null_DEP_DELAY,
  COUNTIF(TAXI_OUT IS NULL) AS null_TAXI_OUT,
  COUNTIF(WHEELS_OFF IS NULL) AS null_WHEELS_OFF,
  COUNTIF(WHEELS_ON IS NULL) AS null_WHEELS_ON,
  COUNTIF(TAXI_IN IS NULL) AS null_TAXI_IN,
  COUNTIF(CRS_ARR_TIME IS NULL) AS null_CRS_ARR_TIME,
  COUNTIF(ARR_TIME IS NULL) AS null_ARR_TIME,
  COUNTIF(ARR_DELAY IS NULL) AS null_ARR_DELAY,
  COUNTIF(CANCELLED IS NULL) AS null_CANCELLED,
  COUNTIF(CANCELLATION_CODE IS NULL) AS null_CANCELLATION_CODE,
  COUNTIF(DIVERTED IS NULL) AS null_DIVERTED,
  COUNTIF(CRS_ELAPSED_TIME IS NULL) AS null_CRS_ELAPSED_TIME,
  COUNTIF(ELAPSED_TIME IS NULL) AS null_ELAPSED_TIME,
  COUNTIF(AIR_TIME IS NULL) AS null_AIR_TIME,
  COUNTIF(DISTANCE IS NULL) AS null_DISTANCE,
  COUNTIF(DELAY_DUE_CARRIER IS NULL) AS null_DELAY_DUE_CARRIER,
  COUNTIF(DELAY_DUE_WEATHER IS NULL) AS null_DELAY_DUE_WEATHER,
  COUNTIF(DELAY_DUE_NAS IS NULL) AS null_DELAY_DUE_NAS,
  COUNTIF(DELAY_DUE_SECURITY IS NULL) AS null_DELAY_DUE_SECURITY,
  COUNTIF(DELAY_DUE_LATE_AIRCRAFT IS NULL) AS null_DELAY_DUE_LATE_AIRCRAFT,
  COUNTIF(FL_YEAR IS NULL) AS null_FL_YEAR,
  COUNTIF(FL_MONTH IS NULL) AS null_FL_MONTH,
  COUNTIF(FL_DAY IS NULL) AS null_FL_DAY
FROM `proyecto4-vuelos.dataset_vuelos.flights_202301`;

-- Query para duplicados en combinacion 
WITH Duplicates AS (
  SELECT
    FL_DATE,
    AIRLINE_CODE,
    FL_NUMBER,
    ORIGIN,
    DEST,
    CRS_DEP_TIME,
    DEP_TIME,
    WHEELS_OFF,
    WHEELS_ON,
    COUNT(*) AS count
  FROM
    `proyecto4-vuelos.dataset_vuelos.flights_202301`
  GROUP BY
    FL_DATE,
    AIRLINE_CODE,
    FL_NUMBER,
    ORIGIN,
    DEST,
    CRS_DEP_TIME,
    DEP_TIME,
    WHEELS_OFF,
    WHEELS_ON
  HAVING
    count > 1
)
SELECT
  f.*
FROM
  `proyecto4-vuelos.dataset_vuelos.flights_202301` f
JOIN
  Duplicates d
ON
  f.FL_DATE = d.FL_DATE
  AND f.AIRLINE_CODE = d.AIRLINE_CODE
  AND f.FL_NUMBER = d.FL_NUMBER
  AND f.ORIGIN = d.ORIGIN
  AND f.DEST = d.DEST
  AND f.CRS_DEP_TIME = d.CRS_DEP_TIME
  AND f.DEP_TIME = d.DEP_TIME
  AND f.WHEELS_OFF = d.WHEELS_OFF
  AND f.WHEELS_ON = d.WHEELS_ON
ORDER BY
  f.FL_DATE,
  f.AIRLINE_CODE,
  f.FL_NUMBER,
  f.ORIGIN,
  f.DEST,
  f.CRS_DEP_TIME,
  f.DEP_TIME,
  f.WHEELS_OFF,
  f.WHEELS_ON
; 