-- Query para manejar nulos
-- Imputacion simple 
SELECT
  FL_DATE,
  AIRLINE_CODE,
  DOT_CODE,
  FL_NUMBER,
  ORIGIN,
  ORIGIN_CITY,
  DEST,
  DEST_CITY,
  CRS_DEP_TIME,
  COALESCE(DEP_TIME, 0) AS DEP_TIME,
  COALESCE(DEP_DELAY, 0) AS DEP_DELAY,
  COALESCE(TAXI_OUT, 0) AS TAXI_OUT,
  COALESCE(WHEELS_OFF, 0) AS WHEELS_OFF,
  COALESCE(WHEELS_ON, 0) AS WHEELS_ON,
  COALESCE(TAXI_IN, 0) AS TAXI_IN,
  COALESCE(ARR_TIME, 0) AS ARR_TIME,
  COALESCE(ARR_DELAY, 0) AS ARR_DELAY,
  CANCELLED,
  CANCELLATION_CODE,
  DIVERTED,
  CRS_ELAPSED_TIME,
  COALESCE(ELAPSED_TIME, 0) AS ELAPSED_TIME,
  COALESCE(AIR_TIME, 0) AS AIR_TIME,
  DISTANCE,
  COALESCE(DELAY_DUE_CARRIER, 0) AS DELAY_DUE_CARRIER,
  COALESCE(DELAY_DUE_WEATHER, 0) AS DELAY_DUE_WEATHER,
  COALESCE(DELAY_DUE_NAS, 0) AS DELAY_DUE_NAS,
  COALESCE(DELAY_DUE_SECURITY, 0) AS DELAY_DUE_SECURITY,
  COALESCE(DELAY_DUE_LATE_AIRCRAFT, 0) AS DELAY_DUE_LATE_AIRCRAFT,
  FL_YEAR,
  FL_MONTH,
  FL_DAY
FROM
  `proyecto4-vuelos.dataset_vuelos.flights_202301`
WHERE
  CRS_ELAPSED_TIME IS NOT NULL;